/*
   RISC-V machine interrupts.
   SPDX-License-Identifier: Unlicense

   https://five-embeddev.com/

*/

#ifndef RISCV_INTERRUPTS_H
#define RISCV_INTERRUPTS_H

enum {
    RISCV_INT_POS_MSI = 3,
    RISCV_INT_POS_MTI = 7,
    RISCV_INT_POS_MEI = 11,
    RISCV_INT_POS_SSI = 1,
    RISCV_INT_POS_STI = 5,
    RISCV_INT_POS_SEI = 9,
    RISCV_INT_POS_USI = 0,
    RISCV_INT_POS_UTI = 4,
    RISCV_INT_POS_UEI = 8,
};

enum {
    RISCV_INT_MASK_MSI = (1UL<<RISCV_INT_POS_MSI),
    RISCV_INT_MASK_MTI = (1UL<<RISCV_INT_POS_MTI),
    RISCV_INT_MASK_MEI = (1UL<<RISCV_INT_POS_MEI),
    RISCV_INT_MASK_SSI = (1UL<<RISCV_INT_POS_SSI),
    RISCV_INT_MASK_STI = (1UL<<RISCV_INT_POS_STI),
    RISCV_INT_MASK_SEI = (1UL<<RISCV_INT_POS_SEI),
    RISCV_INT_MASK_USI = (1UL<<RISCV_INT_POS_USI),
    RISCV_INT_MASK_UTI = (1UL<<RISCV_INT_POS_UTI),
    RISCV_INT_MASK_UEI = (1UL<<RISCV_INT_POS_UEI),
};


#endif /* RISCV_INTERRUPTS_H */
